In [1]:
from sklearn import datasets

In [2]:
cali=datasets.fetch_california_housing()
X=cali.data
Y=cali.target

In [3]:
X.shape

(20640, 8)

In [4]:
import pandas as pd
df=pd.DataFrame(X)
print(cali.feature_names)
df.columns=cali.feature_names
print(type(df.columns))
# add 1 extra feature/column of 2 dimensional
# print(type(df.MedInc))
# print(df.MedInc.count()) #count->20640
# df["Medinc_Medinc"]=df.MedInc**2
# X2=df.values
# print(X2)
# print(X2.shape) #X2.shape->(20640,9) as it is prev 8,
# add 1 feature becomes 9
df.describe()
# print(df.values[0])
# type(cali.feature_names)
# print(cali.feature_names[0])

['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']
<class 'pandas.core.indexes.base.Index'>

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,3.870671,28.639486,5.429000,1.096675,1425.476744,3.070655,35.631861,-119.569704
std,1.899822,12.585558,2.474173,0.473911,1132.462122,10.386050,2.135952,2.003532
min,0.499900,1.000000,0.846154,0.333333,3.000000,0.692308,32.540000,-124.350000
25%,2.563400,18.000000,4.440716,1.006079,787.000000,2.429741,33.930000,-121.800000
50%,3.534800,29.000000,5.229129,1.048780,1166.000000,2.818116,34.260000,-118.490000
75%,4.743250,37.000000,6.052381,1.099526,1725.000000,3.282261,37.710000,-118.010000
max,15.000100,52.000000,141.909091,34.066667,35682.000000,1243.333333,41.950000,-114.310000

In [5]:
# to access a certain column in our dataframe
# first arg (:) signifies which rows we would like to index
# second arg("MedInc") lets us index the column
df.loc[:,"MedInc"]
# iloc gets integer val indices
df.iloc[:,0]

0        8.3252
1        8.3014
2        7.2574
3        5.6431
4        3.8462
          ...
20635    1.5603
20636    2.5568
20637    1.7000
20638    1.8672
20639    2.3886
Name: MedInc, Length: 20640, dtype: float64

In [6]:
for i in range(0,len(cali.feature_names)):
    val=df.iloc[:,i]**2
    ans=df.columns[i]+"_"+df.columns[i]
    df[ans]=val
df.describe()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedInc_MedInc,HouseAge_HouseAge,AveRooms_AveRooms,AveBedrms_AveBedrms,Population_Population,AveOccup_AveOccup,Latitude_Latitude,Longitude_Longitude
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,2.064000e+04,2.064000e+04,20640.000000,20640.000000
mean,3.870671,28.639486,5.429000,1.096675,1425.476744,3.070655,35.631861,-119.569704,18.591242,978.608769,35.595274,1.427277,3.314392e+06,1.172937e+02,1274.191621,14300.928169
std,1.899822,12.585558,2.474173,0.473911,1132.462122,10.386050,2.135952,2.003532,21.946544,750.695219,201.360804,9.916445,1.324852e+07,1.119238e+04,154.386369,480.328440
min,0.499900,1.000000,0.846154,0.333333,3.000000,0.692308,32.540000,-124.350000,0.249900,1.000000,0.715976,0.111111,9.000000e+00,4.792899e-01,1058.851600,13066.776100
25%,2.563400,18.000000,4.440716,1.006079,787.000000,2.429741,33.930000,-121.800000,6.571020,324.000000,19.719961,1.012195,6.193690e+05,5.903642e+00,1151.244900,13926.360100
50%,3.534800,29.000000,5.229129,1.048780,1166.000000,2.818116,34.260000,-118.490000,12.494811,841.000000,27.343788,1.099941,1.359556e+06,7.941776e+00,1173.747600,14039.880100
75%,4.743250,37.000000,6.052381,1.099526,1725.000000,3.282261,37.710000,-118.010000,22.498421,1369.000000,36.631315,1.208958,2.975625e+06,1.077324e+01,1422.044100,14835.240000
max,15.000100,52.000000,141.909091,34.066667,35682.000000,1243.333333,41.950000,-114.310000,225.003000,2704.000000,20138.190083,1160.537778,1.273205e+09,1.545878e+06,1759.802500,15462.922500

In [13]:
# access the value of first row first col->[0][0]th index value
print(df.values[0][0])

8.3252

In [9]:
from sklearn import model_selection
X2=df.values
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X,Y,random_state=0)
X2_train, X2_test, Y2_train, Y2_test = model_selection.train_test_split(X2,Y,random_state=0)
print(X2_train.shape)
print(X2_test.shape)
print(Y2_train.shape)
print(Y2_test.shape)
print(type(X_train))
# X_train

(15480, 16)
(5160, 16)
(15480,)
(5160,)
<class 'numpy.ndarray'>

In [10]:
from sklearn.linear_model import LinearRegression
alg1=LinearRegression()
alg2=LinearRegression()

In [11]:
alg1.fit(X_train,Y_train)
alg2.fit(X2_train,Y2_train)

LinearRegression()

In [12]:
Y_pred=alg1.predict(X_test)
train_score=alg1.score(X_train,Y_train)
test_score=alg1.score(X_test,Y_test)
print("Train score: ",train_score)
print("Test score: ",test_score)
train2_score=alg2.score(X2_train,Y2_train)
test2_score=alg2.score(X2_test,Y2_test)
print("Train score: ",train2_score)
print("Test score: ",test2_score)

Train score:  0.6109633715458154
Test score:  0.5911695436410471
Train score:  0.633812633569431
Test score:  -0.7201080333903687